apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-model-key
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  MODEL_ENCRYPTION_KEY: {{ .Values.modelEncryptionKey | quote }}
