apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-seismic-resource-policy
  namespace: trustee-operator-system
data:
  policy.rego: |
    package policy
    import rego.v1

    default allow = false

    allow if {
        some _, submod in input.submods
        executables := submod["ear.trustworthiness-vector"]["executables"]
        executables >= 2
        executables <= 31
    }
